---
title: 'Revision history for swfdr repository'
author: "Nathan (Nat) Goodman"
date: "October 4, 2017"
output:
  github_document:
    html_preview: no
  html_document:
    css: css/html_document.css
    highlight: kate
  pdf_document: default
linkcolor: cyan
citecolor: green
urlcolor: blue
---
<!-- NEWS.md is generated from NEWS.Rmd. Please edit that file -->

## Release 0.91 2017-10-09 (not yet released)

Documents revised to reflect comments of external readers.

- As suggested by Daniel Lakens, I added [Sholom Wacholder et al's 2004 paper](https://academic.oup.com/jnci/article/96/6/434/2606750/) "Assessing the Probability That a Positive Report is False: An Approach for Molecular Epidemiology Studies" as the earliest work on the subject instead of saying that [John Ioannidis’s 2004 paper](http://dx.plos.org/10.1371/journal.pmed.0020124), “Why most published research findings are false” started it all.
- Inspired by Will Gervais's comments, I changed "case #3" in the discussion to explain that this sometimes improves the hypothesis and sometimes not.
- As suggested by Will Gervais, I added [Paul Smaldino and Richard McElreath's paper](http://rsos.royalsocietypublishing.org/content/3/9/160384) "The natural selection of bad science" to my brief discussion of "Publish or Perish".

## Release 0.90 2017-10-04

First version. Ready for feedback from external readers.

## Copyright & License

Copyright (c) 2017 Nathan Goodman

The software is **open source and free**, released under the [MIT License](https://opensource.org/licenses/MIT). The documentation is **open access**, released under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0).
